from PyQt5 import QtCore, QtGui, QtWidgets


class LoginForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 300))
        Form.setMaximumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("python-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 30, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("python-icon.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 30, 381, 51))
        self.label_2.setMinimumSize(QtCore.QSize(381, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.editUsername = QtWidgets.QLineEdit(Form)
        self.editUsername.setGeometry(QtCore.QRect(180, 100, 113, 20))
        self.editUsername.setObjectName("editUsername")
        self.editPassword = QtWidgets.QLineEdit(Form)
        self.editPassword.setGeometry(QtCore.QRect(180, 140, 113, 20))
        self.editPassword.setObjectName("editPassword")
        self.buttonLogin = QtWidgets.QPushButton(Form)
        self.buttonLogin.setGeometry(QtCore.QRect(190, 190, 75, 31))
        self.buttonLogin.setObjectName("buttonLogin")
        self.buttonRegister = QtWidgets.QPushButton(Form)
        self.buttonRegister.setGeometry(QtCore.QRect(420, 260, 75, 31))
        self.buttonRegister.setObjectName("buttonRegister")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Log in"))
        self.label_2.setText(_translate("Form", "Object Detection App"))
        self.editUsername.setPlaceholderText(_translate("Form", "Login"))
        self.editPassword.setPlaceholderText(_translate("Form", "Password"))
        self.buttonLogin.setText(_translate("Form", "Log in"))
        self.buttonRegister.setText(_translate("Form", "Register"))
